blank_issues_enabled: false
contact_links:
  - name: FAQs
    url: https://github.com/school-cheating/SEBPatch/wiki/FAQs
    about: Before opening an issue, check out the FAQs. Any issue corresponding to the FAQs will be ignored and closed.
